## 랜더스 원정 경기

랜더스 = SK
LG = LG
NC = NC
롯데 = LT
두산 = OB
기아 = HT
삼성 = SS
kt = kt
키움 = WO
한화 = HH
상무 = SM

In [116]:
import urllib.request as req
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import openpyxl
from openpyxl import load_workbook

url = "https://www.koreabaseball.com/Futures/Schedule/BoxScore.aspx?leagueId=2&seriesId=0&gameId=20230917SKOB0&seasonId=2023"
html = req.urlopen(url)
soup = BeautifulSoup(html, 'html.parser')

In [117]:
awayplayerlist = []
awaypositionlist = []
awaypitcherlist = []
awaypitcherposlist = []

awaydiv_list = soup.find_all('div', {'class' : 'tbl-type03 tbl-futures03 data1 mb30'}) 
awayth_list = awaydiv_list[0].find_all('th', {'class' : 'name'})
for i in range(len(awayth_list)):
    awayplayerlist.append(awayth_list[i].text)   # 야수 이름
    
awaydiv_list2 = soup.find_all('div', {'class' : 'tbl-type03 tbl-futures03 data1 mb30'}) 
awayth_list2 = awaydiv_list2[0].find_all('th', {'class' : 'pos2'})
for i in range(len(awayth_list2)):
    awaypositionlist.append(awayth_list2[i].text)  # 야수 포지션    
    
awaypitcherdiv_list = soup.find_all('div', {'class' : 'tbl-type03 tbl-futures03 mb30'}) 
awaypitcherth_list = awaypitcherdiv_list[0].find_all('th', {'class' : 'name'})
for i in range(len(awaypitcherth_list)):
    awaypitcherlist.append(awaypitcherth_list[i].text)
    awaypitcherposlist.append(awaypitcherth_list[i].text)  # 투수 이름

for i in range(0,len(awaypitcherlist)):
    if i == 0:
        awaypitcherposlist[0] = '선발'
    else:
        awaypitcherposlist[i] = '구원'    # 투수 보직

In [118]:
awayplayers_df = pd.DataFrame(awayplayerlist)
awaypositionlist_df = pd.DataFrame(awaypositionlist)
awayplayers = pd.concat([awaypositionlist_df,awayplayers_df],axis = 1).transpose()

awaypitcher_df = pd.DataFrame(awaypitcherlist).transpose()
awaypitcherpos_df = pd.DataFrame(awaypitcherposlist).transpose()
awaypitchers = pd.concat([awaypitcherpos_df, awaypitcher_df],axis = 0)

awaygame = pd.concat([awayplayers, awaypitchers], axis = 1)

awaygame

,0,1,2,3,4,5,6,7,8,9,10,11,12,0,1,2,3
0,三二,중우,二,타一,좌,주,지,一三,우,우,주중,포,유,선발,구원,구원,구원
0,김찬형,김정민,최준우,이거연,류효승,최경모,전의산,고명준,김규남,최유빈,채현우,전경원,김민준,이기순,김주한,박시후,김주온

In [119]:
path = r"C:\py_source\야구 크롤링\0917ganghwa.xlsx"

writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
awaygame.to_excel(writer, index = False)
writer.save()

## 랜더스 홈 경기

In [140]:
import urllib.request as req
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import openpyxl
from openpyxl import load_workbook

url = "https://www.koreabaseball.com/Futures/Schedule/BoxScore.aspx?leagueId=2&seriesId=0&gameId=20230924HHSK0&seasonId=2023"
html = req.urlopen(url)
soup = BeautifulSoup(html, 'html.parser')

In [141]:
homeplayerlist = []
homepositionlist = []
homepitcherlist = []
homepitcherposlist = []

homediv_list = soup.find_all('div', {'class' : 'tbl-type03 tbl-futures03 data1 mb30'}) 
hometh_list = homediv_list[1].find_all('th', {'class' : 'name'})
for i in range(len(hometh_list)):
    homeplayerlist.append(hometh_list[i].text)   # 야수 이름
    
homediv_list2 = soup.find_all('div', {'class' : 'tbl-type03 tbl-futures03 data1 mb30'}) 
hometh_list2 = homediv_list2[1].find_all('th', {'class' : 'pos2'})  
for i in range(len(hometh_list2)):
    homepositionlist.append(hometh_list2[i].text)   # 야수 포지션

homepitcherdiv_list = soup.find_all('div', {'class' : 'tbl-type03 tbl-futures03 mb30'}) 
homepitcherth_list = homepitcherdiv_list[1].find_all('th', {'class' : 'name'})
for i in range(len(homepitcherth_list)):
    homepitcherlist.append(homepitcherth_list[i].text)
    homepitcherposlist.append(homepitcherth_list[i].text)  # 투수 이름

for i in range(0,len(homepitcherlist)):
    if i == 0:
        homepitcherposlist[0] = '선발'
    else:
        homepitcherposlist[i] = '구원'     # 투수 보직

In [142]:
homeplayers_df = pd.DataFrame(homeplayerlist)
homepositionlist_df = pd.DataFrame(homepositionlist)
homeplayers= pd.concat([homepositionlist_df,homeplayers_df],axis = 1).transpose()

homepitcher_df = pd.DataFrame(homepitcherlist).transpose()
homepitcherpos_df = pd.DataFrame(homepitcherposlist).transpose()
homepitchers = pd.concat([homepitcherpos_df, homepitcher_df],axis = 0)

homegame = pd.concat([homeplayers, homepitchers], axis = 1)

homegame

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,0,1,2,3,4,5,6
0,우,좌,타좌,二,二,포,포,지,타지,一,...,중,중,유,선발,구원,구원,구원,구원,구원,구원
0,이정범,박세직,김규남,최준우,최유빈,전경원,김건이,김건웅,이재원,이거연,...,김정민,채현우,김민준,류현곤,박시후,김주온,서동민,백승건,김도현,한두솔

In [143]:
path = r"C:\py_source\야구 크롤링\0924ganghwa.xlsx"

writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
homegame.to_excel(writer, index = False)
writer.save()