In [ ]:
!pip install python-docx

In [ ]:
import urllib.request as req
from bs4 import BeautifulSoup
from docx import Document

In [1]:
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains     #javascript 조작을 돕는 action chains
from bs4 import BeautifulSoup
import pandas as pd
import time
import warnings
warnings.filterwarnings(action='ignore')

from PIL import Image
import urllib.request as req
import openpyxl as xls

In [2]:
driver = webdriver.Chrome('chromedriver.exe')
url = '''http://www.statiz.co.kr/stat.php?mid=stat&re=1&ys=2023&ye=2023&se=0&te=&tm=&ty=0&qu=all&po=0&as=&ae=&hi=&un=&pl=&da=1&o1=WAR&o2=OutCount&de=1&lr=0&tr=&cv=&ml=1&sn=30&pa=240&si=&cn='''
driver.get(url)
driver.maximize_window()

In [30]:
frame0 = pd.DataFrame(columns = range(0,25))

In [31]:
for num in range(3,20):
    xpath = '''//*[@id="fixcol"]/table/tbody/tr[{}]/td[2]/a'''.format(num)
    try:
        pitcher0 = driver.find_element_by_xpath(xpath)
        pitcher0.click()
        xpath1 = '''/html/body/div/div[1]/div/section[2]/div/div[1]/div/div[3]/div/div[2]/table/tbody/tr/td/a[8]'''
        pitcher1 = driver.find_element_by_xpath(xpath1)
        pitcher1.click()
        time.sleep(1)
        xpath2 = '''/html/body/div/div[1]/div/section[2]/div/div[2]/div/div[3]/div/a[3]'''
        pitcher2 = driver.find_element_by_xpath(xpath2)
        pitcher2.click()
        html = req.urlopen(driver.current_url)
        soup = BeautifulSoup(html, 'html.parser')
        content = soup.find_all('div', {'class' : 'col-xs-12 col-sm-4'})
        number = content[1].find_all('font')
        number1 = []
        for i in number:
            number1.append(i.get_text())
        driver.back()
        driver.back()
        driver.back()
        frame1 = pd.DataFrame(number1).transpose()
        frame0 = pd.concat([frame0, frame1], ignore_index=True)
    except Exception as e:
        print(f"예외 발생: {e}")
        pass

예외 발생: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="fixcol"]/table/tbody/tr[13]/td[2]/a"}
  (Session info: chrome=118.0.5993.118)

예외 발생: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="fixcol"]/table/tbody/tr[14]/td[2]/a"}
  (Session info: chrome=118.0.5993.118)

In [32]:
frame0

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,1,2,4,3,9,3,7,8,12,4,...,13,13,8,13,5,6,8,3,,
1,3,7,3,13,17,5,11,10,9,12,...,14,6,14,7,1,7,5,1,4,2
2,,1,1,,1,2,1,2,1,7,...,4,1,4,2,4,2,2,,1,
3,1,1,,2,1,1,3,5,3,1,...,4,4,5,,1,3,1,,,
4,2,7,20,16,13,3,9,16,13,4,...,2,7,12,5,1,3,4,3,,
5,1,3,4,6,14,4,10,15,18,22,...,29,23,20,9,4,11,12,4,5,1
6,3,7,19,24,28,9,9,27,15,14,...,19,18,14,8,3,16,6,5,6,
7,32,41,21,14,6,20,28,34,23,15,...,6,15,16,18,23,2,2,13,9,5
8,9,11,21,12,15,14,24,19,28,25,...,12,18,22,22,30,6,4,11,15,11
9,,,,,,,,,,,...,,,,,,,,,,
10,7,9,16,18,20,11,14,16,14,15,...,16,14,11,13,11,4,8,6,5,7
11,1,3,2,5,3,5,2,11,5,7,...,16,11,11,10,11,6,5,2,4,2
12,,,,,,,,,,,...,,,,,,,,,,
13,18,20,22,34,15,11,17,22,11,14,...,16,18,29,18,11,17,27,22,14,6
14,2,2,10,1,5,6,6,13,6,4,...,13,12,7,2,2,8,4,4,2,

In [33]:
path = r"C:\py_source\야구 크롤링\pitch24.xlsx"

writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
frame0.to_excel(writer, index = False)
writer.save()

In [ ]:
//*[@id="fixcol"]/table/tbody/tr[29]/td[2]/a

In [ ]:
//*[@id="fixcol"]/table/tbody/tr[19]/td[2]/a

In [ ]:
url = '''http://www.statiz.co.kr/player.php?opt=10&sopt=0&name=%EB%B7%B0%EC%BA%90%EB%84%8C&birth=1989-05-11&re=3&da=1&lg=&year=2023'''
html = req.urlopen(url)
soup = BeautifulSoup(html, 'html.parser')

In [ ]:
content = soup.find_all('div', {'class' : 'col-xs-12 col-sm-4'})

In [ ]:
soup

In [ ]:
number = content[1].find_all('font')

In [ ]:
number1 = []

for i in number:
    number1.append(i.get_text())

In [ ]:
number1

In [ ]:
xpath = '''//*[@id="fixcol"]/table/tbody/tr[3]/td[2]/a'''

In [ ]:
'''//*[@id="fixcol"]/table/tbody/tr[4]/td[2]/a'''

In [ ]:
'''//*[@id="fixcol"]/table/tbody/tr[36]/td[2]/a'''

In [ ]:
//*[@id="fixcol"]/table/tbody/tr[24]/td[2]/a

In [ ]:
//*[@id="fixcol"]/table/tbody/tr[20]/td[2]/a

In [ ]:
//*[@id="fixcol"]/table/tbody/tr[19]/td[2]/a

In [ ]:
pitcher0 = driver.find_element_by_xpath(xpath)
pitcher0.click()

In [ ]:
xpath = '''//*[@id="fixcol"]/table/tbody/tr[4]/td[2]/a'''
driver.find_element_by_xpath(xpath)
pitcher0 = driver.find_element_by_xpath(xpath)
pitcher0.click()
xpath1 = '''/html/body/div/div[1]/div/section[2]/div/div[1]/div/div[3]/div/div[2]/table/tbody/tr/td/a[8]'''
pitcher1 = driver.find_element_by_xpath(xpath1)
pitcher1.click()
xpath2 = '''/html/body/div/div[1]/div/section[2]/div/div[2]/div/div[3]/div/a[3]'''
pitcher2 = driver.find_element_by_xpath(xpath2)
pitcher2.click()
html = req.urlopen(driver.current_url)
soup = BeautifulSoup(html, 'html.parser')
content = soup.find_all('div', {'class' : 'col-xs-12 col-sm-4'})
number = content[1].find_all('font')
for i in number:
    number1.append(i.get_text())
driver.back()
driver.back()
driver.back()

In [ ]:
number1

In [ ]:
for num in range(3,5):
    xpath = '''//*[@id="fixcol"]/table/tbody/tr[{}]/td[2]/a'''.format(num)

In [ ]:
xpath

In [ ]:
content = soup.find_all('div', {'class' : 'content-wrap'})
content1 = content[0].text
content2 = content1.replace("\n", "")
content3 = content2.replace("\xa0", "")

In [ ]:
from docx import Document
doc = Document()
doc.add_paragraph(content3)
doc.save('shirt.docx')

In [ ]:
content[0].find_all('p', {'class' : 'dropcap'})

In [ ]:
url = "https://theathletic.com/4557929/2023/05/28/eric-murray-umpire-veteran/"
headers = {'User-Agent':'Chrome/113.0.5672.93'} # 현재 크롬 버전, 오류나면 66.0.3359.181로
req1 = req.Request(url, headers=headers)
html = req.urlopen(req1)
soup = BeautifulSoup(html, 'html.parser')
article = soup.find_all('div', {'class' : 'sc-294a6039-6 fbDgKK article-content-container bodytext1'}) 

alist = []
for i in article:
    alist.append(i.text)

print(alist)  ## 본문 뽑아내기

In [ ]:
from docx import Document
doc = Document()
doc.add_paragraph(alist)
doc.save('title.docx') # 워드 문서 저장, 이하는 실험한 내용들

In [ ]:
article = soup.find_all('div', {'class' : 'sc-294a6039-6 fbDgKK article-content-container bodytext1'})

In [ ]:
print(article)

In [ ]:
alist = []
for i in article:
    alist.append(i.text)

In [ ]:
alist

In [ ]:
!pip install python-docx # 파이썬 새로 깔았을 경우